SEPARATOR = ","
APP_TITLE = "Notas PDF"
CONFIG_FILE = "config.ini"
DEFAULT_OUTPUT_DIR_NAME = "output"
KEY_VALUES = ["VALOR PRINCIPAL", "VALOR NOMINAL", "VALOR TOTAL", "VALOR"]
BANK_ACRONYMS = {
    "BANCO DO BRASIL": "BB",
    "BRADESCO": "BRADESCO",
    "CAIXA": "CEF",
}
